words = [
    "Aggr",
    "Automatiqal",
    "CLI",
    "ESM",
    "EXWW",
    "JHDRW",
    "Matiq",
    "Matiq",
    "Miralem",
    "Publiqate",
    "Publiqate",
    "Qlik's",
    "Wunderlich",
    "appdetails",
    "autoplay",
    "checkscript",
    "extrahead",
    "fontawesome",
    "getscript",
    "inlinehilite",
    "inlinehilite",
    "keyscan",
    "linenums",
    "linenums",
    "materialx",
    "mkdocs",
    "nodata",
    "pygments",
    "pygments",
    "pymdownx",
    "pymdownx",
    "qse",
    "qvf",
    "qvs",
    "runbooks",
    "setscript",
    "shimataro",
    "smartsymbols",
    "smartsymbols",
    "superfences",
    "superfences",
    "twemoji",
    "winform",
    "xrfkey",
]
