# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json?raw=true

site_name: Informatiqal
repo_url: https://github.com/Informatiqal
repo_name: I N F O R M A T I Q A L
theme:
  name: material
  features:
    # - navigation.expand
    - navigation.top
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme: slate)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: default)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
site_url: https://informatiqal.com/
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      lang: en
  - section-index
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      # emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: "index.md"
  - "Automatiqal":
      - automatiqal/index.md
      - "Runbook structure": "automatiqal/runbook-structure.md"
      - "Tasks": "automatiqal/tasks.md"
      - "Events": "automatiqal/events.md"
      - "Operations": "automatiqal/operations.md"
      - "Authentication": "automatiqal/authentication.md"
  - "Automatiqal CLI":
      - automatiqal-cli/index.md
      - "Installation": "automatiqal-cli/install.md"
      - "Runbook structure":
          - "automatiqal-cli/runbook-structure.md"
          - "Task block": "automatiqal-cli/task-details/task-block.md"
          - "Filter/source": "automatiqal-cli/task-details/filter-source.md"
          - "Task options": "automatiqal-cli/task-details/options.md"
          - "onError block": "automatiqal-cli/on-error-block.md"
          - "Operations list": "automatiqal-cli/task-details/operations-list.md"
      - "Authentication": "automatiqal-cli/authentication.md"
      - "Variables":
          - automatiqal-cli/variables/index.md
          - "Dedicated file": "automatiqal-cli/variables/dedicated.md"
          - "Environment": "automatiqal-cli/variables/environment.md"
          - "Global file": "automatiqal-cli/variables/global.md"
          - "Inline": "automatiqal-cli/variables/inline.md"
      - "Schema": "automatiqal-cli/schema.md"
      - "Initial checks": "automatiqal-cli/initial-checks.md"
      - "Output": "automatiqal-cli/output.md"
# TODO: how to configure social cards
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/?h=socia#configuration
