# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json?raw=true

site_name: Informatiqal
repo_url: https://github.com/Informatiqal
repo_name: I N F O R M A T I Q A L
theme:
  name: material
  features:
    # - navigation.expand
    - navigation.top
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "slate"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: default)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
site_url: https://informatiqal.com/
site_description: Informatiqal detailed user documentation
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better
extra_css:
  - stylesheets/extra.css
plugins:
  - rss:
      abstract_chars_count: 160
      comments_path: "null"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      match_path: .*
      pretty_print: false
  - search:
      lang: en
  - section-index
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


nav:
  - Home: "index.md"
  - "Automatiqal":
      - automatiqal/index.md
      - "Runbook structure": "automatiqal/runbook-structure.md"
      - "Tasks": "automatiqal/tasks.md"
      - "Events": "automatiqal/events.md"
      - "Operations": "automatiqal/operations.md"
      - "Authentication": "automatiqal/authentication.md"
  - "Automatiqal CLI":
      - automatiqal-cli/index.md
      - "Installation": "automatiqal-cli/install.md"
      - "Commands": "automatiqal-cli/commands.md"
      - "Runbook structure":
          - "automatiqal-cli/runbook-structure.md"
          - "Task block": "automatiqal-cli/task-details/task-block.md"
          - "Filter/source": "automatiqal-cli/task-details/filter-source.md"
          - "Task options": "automatiqal-cli/task-details/options.md"
          - "onError block": "automatiqal-cli/on-error-block.md"
          - "Operations list": "automatiqal-cli/task-details/operations-list.md"
      - "Authentication": "automatiqal-cli/authentication.md"
      - "Variables":
          - automatiqal-cli/variables/index.md
          - "Dedicated file": "automatiqal-cli/variables/dedicated.md"
          - "Environment": "automatiqal-cli/variables/environment.md"
          - "Global file": "automatiqal-cli/variables/global.md"
          - "Inline": "automatiqal-cli/variables/inline.md"
          - "Reserved variables": "automatiqal-cli/variables/special.md"
      - "Schema": "automatiqal-cli/schema.md"
      - "Initial checks": "automatiqal-cli/initial-checks.md"
      - "Output": "automatiqal-cli/output.md"
      - "Examples": "automatiqal-cli/examples.md"
  - "Test-O-Matiq":
      - test-o-matiq/index.md
      - "Structure":
          - test-o-matiq/structure/index.md
          - "General": "test-o-matiq/structure/general.md"
          # - "Environment": "test-o-matiq/structure/environment.md"
          - "Props": "test-o-matiq/structure/props.md"
          - "Spec":
              - test-o-matiq/structure/spec/index.md
              - "Meta": test-o-matiq/structure/spec/meta/index.md
              - "Data": test-o-matiq/structure/spec/data/index.md
      - "Alternate states": test-o-matiq/states.md
      - "Events": test-o-matiq/events.md
      - "Future": test-o-matiq/future.md
  - "Test-O-Matiq CLI":
      - test-o-matiq-cli/index.md
  - "Qlik SSE (Node.js)":
      - qlik-sse/index.md
      - "Concepts": qlik-sse/concepts.md
      - "Installation": qlik-sse/install.md
      - "Basic plugin": qlik-sse/basic-sse-plugin.md
      - "SSL setup": qlik-sse/ssl.md
      - "Qlik setup": qlik-sse/qs-setup.md
      - "API": qlik-sse/api.md
      - "Build-in SSE functions": qlik-sse/build-in.md
# TODO: how to configure social cards
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/?h=socia#configuration
